@extends('layouts.app')

@section('main-content')
<br/>
<div class="row">
	<form action="{{ action('AddMemberController@store_member_details') }}" method="post" enctype="multipart/form-data">
        <!-- <input type="hidden" name="_token" value="{{ csrf_token() }}" /> -->
		<div class="col-md-2"></div>
		<div class="col-md-4">
			<div class="box box-primary">
				<div class="box-body" style="height:349px; padding-top:0">

					<div class="form-group has-feedback">
					<!-- <label>ID</label> -->
						<input type="hidden" class="form-control" value="{{ $new_id }}" name="new_id" required readonly Title="This is an autogenerated field"/>
					</div>


					<div class="form-group has-feedback">
					<label>First Name</label>
						<input type="text" class="form-control" name="first_name" pattern="[A-Za-z\s]+" Title="English letters only"/>
					</div>


					<div class="form-group has-feedback">
					<label>Middle Name</label>
						<input type="text" class="form-control" name="middle_name" pattern="[A-Za-z\s]+" Title="English letters only/Optional Field"/>
					</div>

					<div class="form-group has-feedback">
					<label>Last Name</label>
						<input type="text" class="form-control" name="last_name" pattern="[A-Za-z\s]+" Title="English letters only" required />
					</div>

					<div class="form-group has-feedback">
					<!-- <label>Status</label> -->
						<input type="hidden" class="form-control" name="status" pattern="[0-9]" value="1"/>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-4">
			<div class="box box-primary">
				<div class="box-body" style="height:349px;padding-top:25px;">

                    <div class="form-group has-feedback">
						<label>Username</label>
						<input type="text" class="form-control" name="user_name" pattern="[A-Za-z\s]+" Title="English letters only" required />
					</div>

					<div class="form-group has-feedback">
						<label>Password</label>
						<input type="password" class="form-control" name="_password" required Title="Letters/Numbers/Special Characters"/>
					</div>

					<div class="form-group has-feedback">
						<label>Select a Role</label>
						<select name="select_role" class="form-control" required >
							<option value="">Select role</option>
							<option value="3">Marketing</option>
                            <option value="2">Receptionist</option>
							<option value="4">RCC</option>
							<option value="5">Back Office</option>
							<option value="6">Doctor</option>
							<option value="7">Wellness Director</option>
						</select>
					</div>

                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
					<div class="form-group has-feedback">
						<button type="submit" class="btn btn-primary btn-block btn-flat btn-width">Submit</button>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>
@endsection
